name: Render LaTeX Documents

on:
  push:
    paths:
      - 'D&K Books/*.tex'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install TeXLive
      run: |
        sudo apt-get -y update
        sudo apt-get -y install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra texlive-science

    - name: Compile LaTeX documents
      run: |
        cd "D&K Books"
        for texfile in *.tex; do
            pdflatex "$texfile"
        done

    - name: Commit and push PDFs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add "D&K Books/*.pdf" 
        git commit -m "Update rendered PDFs" || echo "No changes to commit"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/zimoli02/2023-2024-SURFiN-Foraging-Project.git
        git push origin HEAD
