name: Build and Push Multiple LaTeX documents

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tex_file: ['Equation_2.32.tex']
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    
    - name: Install TeXLive
      run: |
        sudo apt-get -y update
        sudo apt-get -y install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra texlive-science # added texlive-science
    
    - name: Compile LaTeX document
      run: |
        cd "D&K Books"
        pdflatex ${{ matrix.tex_file }}
    
    - name: Push PDFs back to repository
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add "D&K Books/*.pdf"
        git commit -m "Add compiled PDFs"
        git push https://${{secrets.LATEX_TOKEN}}@github.com/zimoli02/2023-2024-SURFiN-Foraging-Project.git HEAD:main
